version: '3.6'

services:
  backend:
    build: backend
    hostname: backend-host
    volumes:
      - ./backend:/app
    ports:
      - "9000:9000"
    networks:
      - project-network

  frontend:
    build: frontend
    hostname: frontend-host
    volumes:
      - ./frontend:/app
    environment:
      - BACKEND_URL=http://backend-host:9000
    ports:
      - "8000:8000"
    links:
      - backend
    depends_on:
      - backend
    networks:
      - project-network

networks:
  project-network: {}